---

language: golang

go:
  - 1.14.x
sudo: required
services:
  - docker

before_script:
  - build/set_env.sh

script:
  - docker build -t ubuntu-python .

after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
  - docker tag ubuntu-python corberos/ubuntu-python:latest
  - docker tag ubuntu-python corberos/ubuntu-python:$DOCKER_BUILD_VERSION
  - docker push corberos/ubuntu-python:latest
  - docker push corberos/ubuntu-python:$DOCKER_BUILD_VERSION

env:
  - DOCKER_BUILD_VERSION=$(cat VERSION)